# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo-app
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-demo-app
  template:
    metadata:
      labels:
        app: gitops-demo-app
    spec:
      containers:
      - name: gitops-demo-app
        image: linuxmanl/gitops-demo-app:v24
        ports:
        - containerPort: 3000
        env:
        - name: APP_VERSION
          value: ${IMAGE_TAG}
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
