apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo-app
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-demo-app
  template:
    metadata:
      labels:
        app: gitops-demo-app
    spec:
      containers:
      - name: gitops-demo-app
        image: linuxmanl/gitops-demo-app:latest
        imagePullPolicy: Always  # Important for latest tag
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: gitops-demo-app
  namespace: demo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    name: web
  selector:
    app: gitops-demo-app
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitops-demo-app
  namespace: demo
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`demo.hostingremote.com`)
      kind: Rule
      services:
        - name: gitops-demo-app
          port: 80
  tls:
    secretName: gitops-demo-app-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitops-demo-app-tls
  namespace: demo
spec:
  secretName: gitops-demo-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - demo.hostingremote.com
